
server:
  port: 80
#默认使用配置
spring:
#    use-forward-headers: true
#    address: 127.0.0.1
#    tomcat:
#      remote_ip_header: x-forwarded-for
#      protocol_header: x-forwarded-proto
  datasource:
    druid:
      password: wmfZB*2513148      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false
      max-active: 100
      min-idle: 30
      max-wait: 10000
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
  thymeleaf:
  # 开发时关闭缓存,不然没法看到实时页面
    cache: false
  # 严格的 HTML
    mode: HTML5
    encoding: UTF-8
  #pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
mybatis:
    config-location: classpath:mybatis-config.xml
    type-aliases-package: xyz.yescn.blog.domain
    mapper-locations: classpath:mappers/*.xml

