#默认使用配置
spring:
  server:
    port: 8080
  datasource:
    druid:
      
<<<<<<< .mine
      username: root
=======
      username: gavin
>>>>>>> .theirs
      password: 123456
<<<<<<< .mine
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8
=======
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false
>>>>>>> .theirs
      max-active: 100
      min-idle: 30
      max-wait: 10000
      filter:
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
  thymeleaf:
  # 开发时关闭缓存,不然没法看到实时页面
    cache: false
  # 严格的 HTML
    mode: HTML5
    encoding: UTF-8
  #pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
mybatis:
    config-location: classpath:mybatis-config.xml
    type-aliases-package: xyz.yescn.blog.domain
    mapper-locations: classpath:mappers/*.xml

